spring.application.name=wildrose
spring.datasource.url=jdbc:mysql://localhost:3306/wildrose
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=2007

